### ISSUE TITLE
warning on empty message formatted by glue

### ISSUE THREAD

**Issue by daroczig** [atalv/azlogr#35]
Hi,

While preparing a CRAN update and running the reverse dependency checks for `logger`, I've run into an issue with https://github.com/atalv/azlogr/blob/main/tests/testthat/test-logger_level.R#L161 -- https://github.com/daroczig/logger/pull/147 introduced throwing a warning when `formatter_glue` return no message to note to the user that something is off.

Your above test line explicitly expects no warnings, so the above PR could not go into `main`, and we had to revert the PR.

Would you feel comfortable dropping that test line and accepting a warning from `formatter_glue` when it renders no message? If that's an unwanted behaviour, could you please comment on https://github.com/daroczig/logger/issues/130 so that we can discuss what's a good solution for your use-cases?

Thanks,
Gergely (maintainer of `logger`)

**Comment by atalv** [comment]
Makes sense. I made relevant changes and submitted to CRAN
